In [1]:
import nfl_data_py as nfl, pandas as pd

In [5]:
data_2022 = nfl.import_pbp_data([2021,2022], downcast=True, alt_path=None)
data_2022

2021 done.
2022 done.
Downcasting floats.

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense
0,1.0,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0
1,40.0,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,TEN,home,ARI,...,None,None,NaN,None,NaN,43616;43680;52416;49410;53634;43556;53639;4625...,00-0032560;00-0036356;00-0035705;00-0036896;00...,00-0032496;00-0036652;00-0032355;00-0033455;00...,11.0,11.0
2,55.0,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,TEN,home,ARI,...,SINGLEBACK,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",NaN,52416;49410;38629;53445;43334;47816;47848;3853...,00-0029413;00-0032764;00-0029701;00-0027648;00...,00-0036356;00-0035705;00-0036933;00-0035236;00...,11.0,11.0
3,76.0,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,TEN,home,ARI,...,SHOTGUN,"1 RB, 2 TE, 2 WR",7.0,"3 DL, 4 LB, 4 DB",4.0,52416;49410;38629;53445;43334;47816;47848;3853...,00-0029413;00-0032764;00-0029701;00-0027648;00...,00-0036356;00-0035705;00-0036933;00-0035236;00...,11.0,11.0
4,100.0,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,TEN,home,ARI,...,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"2 DL, 4 LB, 5 DB",4.0,52416;42401;49410;43556;38629;40008;47816;4784...,00-0032355;00-0029413;00-0029701;00-0033455;00...,00-0036356;00-0032127;00-0035705;00-0030528;00...,11.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100854,4035.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0
100855,4024.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,KC,away,PHI,...,None,None,NaN,None,NaN,40994;46152;52618;54026;54478;53552;53492;5454...,00-0030615;00-0034752;00-0036230;00-0036623;00...,00-0036813;00-0037073;00-0036917;00-0037615;00...,11.0,11.0
100856,4050.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,PHI,home,KC,...,None,None,NaN,None,NaN,48259;54724;54568;54600;54026;53579;45102;4251...,00-0035157;00-0037198;00-0037819;00-0038043;00...,00-0036813;00-0036919;00-0033251;00-0036917;00...,11.0,11.0
100857,4072.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,PHI,home,KC,...,SHOTGUN,"1 RB, 1 TE, 3 WR",3.0,"0 DL, 4 LB, 7 DB",2.0,52608;52546;48259;46118;47846;43368;54568;5460...,00-0036271;00-0034351;00-0032954;00-0036919;00...,00-0036374;00-0035157;00-0035625;00-0037819;00...,11.0,11.0
100858,4094.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0

In [6]:
#data_2022.to_parquet('pbp.parquet')

In [2]:
data_2022 = pd.read_parquet('pbp.parquet')
data_2022

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense
0,1.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0
1,37.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,ATL,away,PHI,...,None,None,NaN,None,NaN,44987;46263;45070;42515;42450;45599;34465;4040...,00-0031950;00-0033725;00-0026990;00-0029955;00...,00-0033576;00-0034411;00-0033222;00-0031570;00...,11.0,11.0
2,52.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,ATL,away,PHI,...,None,"2 RB, 1 TE, 2 WR",NaN,"4 DL, 2 LB, 5 DB",NaN,34502;44826;41232;34465;34472;43522;35722;3545...,00-0027027;00-0031279;00-0026997;00-0027215;00...,00-0033876;00-0026990;00-0032803;00-0027865;00...,11.0,11.0
3,75.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,ATL,away,PHI,...,I_FORM,"2 RB, 1 TE, 2 WR",7.0,"4 DL, 2 LB, 5 DB",4.0,34502;44826;41232;34465;34472;43522;43370;3545...,00-0027027;00-0031279;00-0026997;00-0032392;00...,00-0033876;00-0026990;00-0032803;00-0027865;00...,11.0,11.0
4,104.0,2018_01_ATL_PHI,2018090600,PHI,ATL,REG,1,ATL,away,PHI,...,I_FORM,"2 RB, 1 TE, 2 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,34502;44826;41232;34465;34472;43522;35722;3545...,00-0027027;00-0031279;00-0026997;00-0027215;00...,00-0033876;00-0026990;00-0032803;00-0027865;00...,11.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245276,4035.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0
245277,4024.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,KC,away,PHI,...,None,None,NaN,None,NaN,40994;46152;52618;54026;54478;53552;53492;5454...,00-0030615;00-0034752;00-0036230;00-0036623;00...,00-0036813;00-0037073;00-0036917;00-0037615;00...,11.0,11.0
245278,4050.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,PHI,home,KC,...,None,None,NaN,None,NaN,48259;54724;54568;54600;54026;53579;45102;4251...,00-0035157;00-0037198;00-0037819;00-0038043;00...,00-0036813;00-0036919;00-0033251;00-0036917;00...,11.0,11.0
245279,4072.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,PHI,home,KC,...,SHOTGUN,"1 RB, 1 TE, 3 WR",3.0,"0 DL, 4 LB, 7 DB",2.0,52608;52546;48259;46118;47846;43368;54568;5460...,00-0036271;00-0034351;00-0032954;00-0036919;00...,00-0036374;00-0035157;00-0035625;00-0037819;00...,11.0,11.0
245280,4094.0,2022_22_KC_PHI,2023021200,PHI,KC,POST,22,None,None,None,...,None,None,NaN,None,NaN,,,,0.0,0.0

In [8]:
data_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245281 entries, 0 to 245280
Columns: 384 entries, play_id to n_defense
dtypes: float32(204), int32(6), int64(1), object(173)
memory usage: 522.1+ MB

In [16]:
#nfl.import_weekly_data([2023]).head()

Downcasting floats.

,player_id,player_name,player_display_name,position,position_group,headshot_url,recent_team,season,week,season_type,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/private/f_aut...,NYJ,2023,1,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,0.00,0.00
1,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/private/f_aut...,LA,2023,1,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,14.46,14.46
2,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/private/f_aut...,LA,2023,2,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,13.98,13.98
3,00-0028002,R.Cobb,Randall Cobb,WR,WR,https://static.www.nfl.com/image/private/f_aut...,NYJ,2023,1,REG,...,0.0,-3.924131,0,0.0,0.055556,0.133333,0.176667,0.0,0.00,0.00
4,00-0028002,R.Cobb,Randall Cobb,WR,WR,https://static.www.nfl.com/image/private/f_aut...,NYJ,2023,2,REG,...,0.0,-1.523066,0,0.0,0.040000,0.056604,0.099623,0.0,0.00,0.00

In [ ]:
import snowflake.connector

def create_snowflake_schema(data):
    conn = snowflake.connector.connect(
        user='your_username',
        password='your_password',
        account='your_account',
        warehouse='your_warehouse',
        database='your_database',
        schema='your_schema'
    )
    
    cursor = conn.cursor()
    
    # Create the schema
    cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {data}_schema")
    
    # Close the connection
    cursor.close()
    conn.close()

create_snowflake_schema(data_2022)

https://pxtowie-ls78219.snowflakecomputing.com/

In [4]:
data_2022_create_statement = "CREATE TABLE IF NOT EXISTS nfl_stats (\n"

data_2022_columns = data_2022.columns.tolist()

for column in data_2022_columns:
    data_2022_create_statement += f"    {column} STRING,\n"

data_2022_create_statement = data_2022_create_statement.rstrip(",\n") + "\n)"

data_2022_create_statement

'CREATE TABLE IF NOT EXISTS nfl_stats (\n    play_id STRING,\n    game_id STRING,\n    old_game_id STRING,\n    home_team STRING,\n    away_team STRING,\n    season_type STRING,\n    week STRING,\n    posteam STRING,\n    posteam_type STRING,\n    defteam STRING,\n    side_of_field STRING,\n    yardline_100 STRING,\n    game_date STRING,\n    quarter_seconds_remaining STRING,\n    half_seconds_remaining STRING,\n    game_seconds_remaining STRING,\n    game_half STRING,\n    quarter_end STRING,\n    drive STRING,\n    sp STRING,\n    qtr STRING,\n    down STRING,\n    goal_to_go STRING,\n    time STRING,\n    yrdln STRING,\n    ydstogo STRING,\n    ydsnet STRING,\n    desc STRING,\n    play_type STRING,\n    yards_gained STRING,\n    shotgun STRING,\n    no_huddle STRING,\n    qb_dropback STRING,\n    qb_kneel STRING,\n    qb_spike STRING,\n    qb_scramble STRING,\n    pass_length STRING,\n    pass_location STRING,\n    air_yards STRING,\n    yards_after_catch STRING,\n    run_location STRING,\n    run_gap STRING,\n    field_goal_result STRING,\n    kick_distance STRING,\n    extra_point_result STRING,\n    two_point_conv_result STRING,\n    home_timeouts_remaining STRING,\n    away_timeouts_remaining STRING,\n    timeout STRING,\n    timeout_team STRING,\n    td_team STRING,\n    td_player_name STRING,\n    td_player_id STRING,\n    posteam_timeouts_remaining STRING,\n    defteam_timeouts_remaining STRING,\n    total_home_score STRING,\n    total_away_score STRING,\n    posteam_score STRING,\n    defteam_score STRING,\n    score_differential STRING,\n    posteam_score_post STRING,\n    defteam_score_post STRING,\n    score_differential_post STRING,\n    no_score_prob STRING,\n    opp_fg_prob STRING,\n    opp_safety_prob STRING,\n    opp_td_prob STRING,\n    fg_prob STRING,\n    safety_prob STRING,\n    td_prob STRING,\n    extra_point_prob STRING,\n    two_point_conversion_prob STRING,\n    ep STRING,\n    epa STRING,\n    total_home_epa STRING,\n    total_away_epa STRING,\n    total_home_rush_epa STRING,\n    total_away_rush_epa STRING,\n    total_home_pass_epa STRING,\n    total_away_pass_epa STRING,\n    air_epa STRING,\n    yac_epa STRING,\n    comp_air_epa STRING,\n    comp_yac_epa STRING,\n    total_home_comp_air_epa STRING,\n    total_away_comp_air_epa STRING,\n    total_home_comp_yac_epa STRING,\n    total_away_comp_yac_epa STRING,\n    total_home_raw_air_epa STRING,\n    total_away_raw_air_epa STRING,\n    total_home_raw_yac_epa STRING,\n    total_away_raw_yac_epa STRING,\n    wp STRING,\n    def_wp STRING,\n    home_wp STRING,\n    away_wp STRING,\n    wpa STRING,\n    vegas_wpa STRING,\n    vegas_home_wpa STRING,\n    home_wp_post STRING,\n    away_wp_post STRING,\n    vegas_wp STRING,\n    vegas_home_wp STRING,\n    total_home_rush_wpa STRING,\n    total_away_rush_wpa STRING,\n    total_home_pass_wpa STRING,\n    total_away_pass_wpa STRING,\n    air_wpa STRING,\n    yac_wpa STRING,\n    comp_air_wpa STRING,\n    comp_yac_wpa STRING,\n    total_home_comp_air_wpa STRING,\n    total_away_comp_air_wpa STRING,\n    total_home_comp_yac_wpa STRING,\n    total_away_comp_yac_wpa STRING,\n    total_home_raw_air_wpa STRING,\n    total_away_raw_air_wpa STRING,\n    total_home_raw_yac_wpa STRING,\n    total_away_raw_yac_wpa STRING,\n    punt_blocked STRING,\n    first_down_rush STRING,\n    first_down_pass STRING,\n    first_down_penalty STRING,\n    third_down_converted STRING,\n    third_down_failed STRING,\n    fourth_down_converted STRING,\n    fourth_down_failed STRING,\n    incomplete_pass STRING,\n    touchback STRING,\n    interception STRING,\n    punt_inside_twenty STRING,\n    punt_in_endzone STRING,\n    punt_out_of_bounds STRING,\n    punt_downed STRING,\n    punt_fair_catch STRING,\n    kickoff_inside_twenty STRING,\n    kickoff_in_endzone STRING,\n    kickoff_out_of_bounds STRING,\n    kickoff_downed STRING,\n    kickoff_fair_catch STRING,\n    fumble_forced STRING,\n    fumble_not_forced STRING,\n    fumble_out_of_bounds STRING,\n    solo_tackle STRING,\n    safety STRING,\n    penalty STRING,\n    tackled_for_loss STRING,\n    fumble_lost STRING,\n    own_kickoff_recovery STRING,\n    own_kickoff_recovery_td STRING,\n    qb_hit STRING,\n    rush_attempt STRING,\n    pass_attempt STRING,\n    sack STRING,\n    touchdown STRING,\n    pass_touchdown STRING,\n    rush_touchdown STRING,\n    return_touchdown STRING,\n    extra_point_attempt STRING,\n    two_point_attempt STRING,\n    field_goal_attempt STRING,\n    kickoff_attempt STRING,\n    punt_attempt STRING,\n    fumble STRING,\n    complete_pass STRING,\n    assist_tackle STRING,\n    lateral_reception STRING,\n    lateral_rush STRING,\n    lateral_return STRING,\n    lateral_recovery STRING,\n    passer_player_id STRING,\n    passer_player_name STRING,\n    passing_yards STRING,\n    receiver_player_id STRING,\n    receiver_player_name STRING,\n    receiving_yards STRING,\n    rusher_player_id STRING,\n    rusher_player_name STRING,\n    rushing_yards STRING,\n    lateral_receiver_player_id STRING,\n    lateral_receiver_player_name STRING,\n    lateral_receiving_yards STRING,\n    lateral_rusher_player_id STRING,\n    lateral_rusher_player_name STRING,\n    lateral_rushing_yards STRING,\n    lateral_sack_player_id STRING,\n    lateral_sack_player_name STRING,\n    interception_player_id STRING,\n    interception_player_name STRING,\n    lateral_interception_player_id STRING,\n    lateral_interception_player_name STRING,\n    punt_returner_player_id STRING,\n    punt_returner_player_name STRING,\n    lateral_punt_returner_player_id STRING,\n    lateral_punt_returner_player_name STRING,\n    kickoff_returner_player_name STRING,\n    kickoff_returner_player_id STRING,\n    lateral_kickoff_returner_player_id STRING,\n    lateral_kickoff_returner_player_name STRING,\n    punter_player_id STRING,\n    punter_player_name STRING,\n    kicker_player_name STRING,\n    kicker_player_id STRING,\n    own_kickoff_recovery_player_id STRING,\n    own_kickoff_recovery_player_name STRING,\n    blocked_player_id STRING,\n    blocked_player_name STRING,\n    tackle_for_loss_1_player_id STRING,\n    tackle_for_loss_1_player_name STRING,\n    tackle_for_loss_2_player_id STRING,\n    tackle_for_loss_2_player_name STRING,\n    qb_hit_1_player_id STRING,\n    qb_hit_1_player_name STRING,\n    qb_hit_2_player_id STRING,\n    qb_hit_2_player_name STRING,\n    forced_fumble_player_1_team STRING,\n    forced_fumble_player_1_player_id STRING,\n    forced_fumble_player_1_player_name STRING,\n    forced_fumble_player_2_team STRING,\n    forced_fumble_player_2_player_id STRING,\n    forced_fumble_player_2_player_name STRING,\n    solo_tackle_1_team STRING,\n    solo_tackle_2_team STRING,\n    solo_tackle_1_player_id STRING,\n    solo_tackle_2_player_id STRING,\n    solo_tackle_1_player_name STRING,\n    solo_tackle_2_player_name STRING,\n    assist_tackle_1_player_id STRING,\n    assist_tackle_1_player_name STRING,\n    assist_tackle_1_team STRING,\n    assist_tackle_2_player_id STRING,\n    assist_tackle_2_player_name STRING,\n    assist_tackle_2_team STRING,\n    assist_tackle_3_player_id STRING,\n    assist_tackle_3_player_name STRING,\n    assist_tackle_3_team STRING,\n    assist_tackle_4_player_id STRING,\n    assist_tackle_4_player_name STRING,\n    assist_tackle_4_team STRING,\n    tackle_with_assist STRING,\n    tackle_with_assist_1_player_id STRING,\n    tackle_with_assist_1_player_name STRING,\n    tackle_with_assist_1_team STRING,\n    tackle_with_assist_2_player_id STRING,\n    tackle_with_assist_2_player_name STRING,\n    tackle_with_assist_2_team STRING,\n    pass_defense_1_player_id STRING,\n    pass_defense_1_player_name STRING,\n    pass_defense_2_player_id STRING,\n    pass_defense_2_player_name STRING,\n    fumbled_1_team STRING,\n    fumbled_1_player_id STRING,\n    fumbled_1_player_name STRING,\n    fumbled_2_player_id STRING,\n    fumbled_2_player_name STRING,\n    fumbled_2_team STRING,\n    fumble_recovery_1_team STRING,\n    fumble_recovery_1_yards STRING,\n    fumble_recovery_1_player_id STRING,\n    fumble_recovery_1_player_name STRING,\n    fumble_recovery_2_team STRING,\n    fumble_recovery_2_yards STRING,\n    fumble_recovery_2_player_id STRING,\n    fumble_recovery_2_player_name STRING,\n    sack_player_id STRING,\n    sack_player_name STRING,\n    half_sack_1_player_id STRING,\n    half_sack_1_player_name STRING,\n    half_sack_2_player_id STRING,\n    half_sack_2_player_name STRING,\n    return_team STRING,\n    return_yards STRING,\n    penalty_team STRING,\n    penalty_player_id STRING,\n    penalty_player_name STRING,\n    penalty_yards STRING,\n    replay_or_challenge STRING,\n    replay_or_challenge_result STRING,\n    penalty_type STRING,\n    defensive_two_point_attempt STRING,\n    defensive_two_point_conv STRING,\n    defensive_extra_point_attempt STRING,\n    defensive_extra_point_conv STRING,\n    safety_player_name STRING,\n    safety_player_id STRING,\n    season STRING,\n    cp STRING,\n    cpoe STRING,\n    series STRING,\n    series_success STRING,\n    series_result STRING,\n    order_sequence STRING,\n    start_time STRING,\n    time_of_day STRING,\n    stadium STRING,\n    weather STRING,\n    nfl_api_id STRING,\n    play_clock STRING,\n    play_deleted STRING,\n    play_type_nfl STRING,\n    special_teams_play STRING,\n    st_play_type STRING,\n    end_clock_time STRING,\n    end_yard_line STRING,\n    fixed_drive STRING,\n    fixed_drive_result STRING,\n    drive_real_start_time STRING,\n    drive_play_count STRING,\n    drive_time_of_possession STRING,\n    drive_first_downs STRING,\n    drive_inside20 STRING,\n    drive_ended_with_score STRING,\n    drive_quarter_start STRING,\n    drive_quarter_end STRING,\n    drive_yards_penalized STRING,\n    drive_start_transition STRING,\n    drive_end_transition STRING,\n    drive_game_clock_start STRING,\n    drive_game_clock_end STRING,\n    drive_start_yard_line STRING,\n    drive_end_yard_line STRING,\n    drive_play_id_started STRING,\n    drive_play_id_ended STRING,\n    away_score STRING,\n    home_score STRING,\n    location STRING,\n    result STRING,\n    total STRING,\n    spread_line STRING,\n    total_line STRING,\n    div_game STRING,\n    roof STRING,\n    surface STRING,\n    temp STRING,\n    wind STRING,\n    home_coach STRING,\n    away_coach STRING,\n    stadium_id STRING,\n    game_stadium STRING,\n    aborted_play STRING,\n    success STRING,\n    passer STRING,\n    passer_jersey_number STRING,\n    rusher STRING,\n    rusher_jersey_number STRING,\n    receiver STRING,\n    receiver_jersey_number STRING,\n    pass STRING,\n    rush STRING,\n    first_down STRING,\n    special STRING,\n    play STRING,\n    passer_id STRING,\n    rusher_id STRING,\n    receiver_id STRING,\n    name STRING,\n    jersey_number STRING,\n    id STRING,\n    fantasy_player_name STRING,\n    fantasy_player_id STRING,\n    fantasy STRING,\n    fantasy_id STRING,\n    out_of_bounds STRING,\n    home_opening_kickoff STRING,\n    qb_epa STRING,\n    xyac_epa STRING,\n    xyac_mean_yardage STRING,\n    xyac_median_yardage STRING,\n    xyac_success STRING,\n    xyac_fd STRING,\n    xpass STRING,\n    pass_oe STRING,\n    nflverse_game_id STRING,\n    possession_team STRING,\n    offense_formation STRING,\n    offense_personnel STRING,\n    defenders_in_box STRING,\n    defense_personnel STRING,\n    number_of_pass_rushers STRING,\n    players_on_play STRING,\n    offense_players STRING,\n    defense_players STRING,\n    n_offense STRING,\n    n_defense STRING\n)'

In [3]:

import snowflake.connector

def upload_parquet_to_snowflake(parquet_file_path, table_name):
    conn = snowflake.connector.connect(
        user='ACCOUNTADMIN',
        password='Xnk3GvsxPi85Pbs',
        account='LS78219',
        #warehouse='your_warehouse',
        database='nfl_stats',
        schema='public'
    )
    
    cursor = conn.cursor()
    
    # Create the table
    cursor.execute(f"CREATE TABLE IF NOT EXISTS {table_name} LIKE PARQUET '{parquet_file_path}'")
    
    # Copy the data from the parquet file to the table
    cursor.execute(f"COPY INTO {table_name} FROM '{parquet_file_path}' FILE_FORMAT = (TYPE = 'PARQUET')")
    
    # Close the connection
    cursor.close()
    conn.close()

upload_parquet_to_snowflake('pbp.parquet', 'playbyplay')

LibraryNotFoundError: Error detecting the version of libcrypto